---
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: fluent-bit-to-vali
build:
  local:
    useDockerCLI: false
    useBuildkit: true
  artifacts:
    - image: fluent-bit-vali
      docker:
        target: fluent-bit-vali
        cacheFrom:
          - fluent-bit-vali
      sync:
        manual:
          - src: "example/kind/fluent-bit-vali.conf"
            dest: "/fluent-bit/config/fluent-bit.conf"
manifests:
  rawYaml:
  - example/kind/fluent-bit-vali*
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: vali
    namespace: vali
    port: 3100
    localPort: 3100