node:
  master: ${NODE_MASTER}
  name: ${NODE_NAME}
  data: ${NODE_DATA}
  ingest: ${NODE_INGEST}
  max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES}

processors: ${PROCESSORS}

network:
  host: ${NETWORK_HOST}

path:
  data: ${PATH_DATA}
  logs: ${PATH_DATA}/log

http:
  port: ${HTTP_PORT}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

discovery:
  zen:
    ping.unicast.hosts: ${DISCOVERY_SERVICE}
    minimum_master_nodes: ${NUMBER_OF_MASTERS}

transport:
  tcp:
    port: ${TRANSPORT_PORT}

indices:
  memory:
    index_buffer_size: ${INDEX_BUFFER_SIZE}

thread_pool:
  write:
    queue_size: ${WRITE_QUEUE_SIZE}

cluster:
  name: ${CLUSTER_NAME}
  routing:
    allocation:
      disk:
        # disable disk allocation
        threshold_enabled: ${ALLOW_DISK_ALLOCATION}
        watermark:
          # this is the threshold to move shard to other node
          # (which we don't have in single node mode so put it to 100%)
          high : ${DISK_WATERMARK_HIGHT}
          #The low watermark defines the disk usage point beyond which ES 
          # won’t allocate new shards to that node.
          low: ${DISK_WATERMARK_LOW}
          #threshold for read only lock
          flood_stage: ${DISK_WATERMARK_FLOOD_STAGE}
      #for single node only allow only primary shard. We don't need replica
      enable: ${SHARD_REBALANCING_FOR}
